// user
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const GET_USER_DATA = 'GET_USER_DATA' // 用户详情

// topics
export const GET_TOPICS_LIST = 'GET_TOPICS_LIST'
export const GET_TOPICS_KEY = 'GET_TOPICS_KEY'
export const GET_TOPICS_PAGE = 'GET_TOPICS_PAGE'
export const GET_TOPICS_DETAIL = 'GET_TOPICS_DETAIL'
export const SET_REPLY_STATUS = 'SET_REPLY_STATUS'
export const SET_COLLECT_STATUS = 'SET_COLLECT_STATUS'
